import Head from 'next/head';
import {
  Box,
  Divider,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue,
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { FaHome } from "react-icons/fa";
import {
  WalletSection,
  StakingSection,
} from '../components';
import { defaultChainName } from '../config';
import { useState } from 'react';
import { ChainName } from '@cosmos-kit/core';


export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  const [selectedChainName, setChainName] = useState<ChainName | undefined>(
    defaultChainName
  );

  return (
    <Container maxW="5xl" py={10}>
      <Head>
        <title>Celestia + Rollkit + Cosmos SDK
</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex justifyContent="end" mb={4}>
        <Button variant="outline" px={0} onClick={toggleColorMode}>
          <Icon
            as={colorMode === 'light' ? BsFillMoonStarsFill : BsFillSunFill}
          />
        </Button>
        <Button variant="outline" px={0} ml={2} onClick={() => window.location.href = "/"}>
          <Icon
            as={FaHome}
          />
        </Button>
      </Flex>
      <Box textAlign="center">
        <Heading
          as="h1"
          fontSize={{ base: '3xl', sm: '4xl', md: '5xl' }}
          fontWeight="extrabold"
          mb={3}
        >
          Celestia + Rollkit + Cosmos SDK
        </Heading>
        <Heading
          as="h1"
          fontWeight="bold"
          fontSize={{ base: '2xl', sm: '3xl', md: '4xl' }}
        >
          <Text as="span">Welcome to&nbsp;</Text>
          <Text
            as="span"
            color={useColorModeValue('primary.500', 'primary.200')}
          >
            CosmosKit + Next.js + Celestia + Rollkit
          </Text>
        </Heading>
      </Box>
      <WalletSection
        isMultiChain={true}
        providedChainName={selectedChainName}
        setChainName={setChainName}
      />
      <Divider />
      {/* {selectedChainName && <StakingSection chainName={selectedChainName} />} */}
      <Box mb={3}>
        <Divider />
      </Box>
      <Stack
        isInline={true}
        spacing={1}
        justifyContent="center"
        opacity={0.5}
        fontSize="sm"
      >
        <Text>Built with</Text>
        <Link
          href="https://cosmology.tech/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Cosmology
        </Link>
      </Stack>
    </Container>
  );
}
